management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka-server/eureka/
      
logging:
  file: ${spring.application.name}.log
  
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'
  
facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
    
info:
  app:
    name: ${spring.application.name}
    description: Authorization Server for authorizing users and applications
  tech:
    - Java-8
    - Spring Boot
    - Spring Cloud Eureka Client
    - Spring Boot Admin Client
    - Spring Boot Oauth Security
    - Spring Boot Authorization Server
    