spring:
  boot:
    admin:
      client:
        url: http://localhost:9000/monitoring-service/admin

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8080/me

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka-server/eureka/
      
logging:
  file: ${spring.application.name}.log
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
  
info:
  app:
    name: ${spring.application.name}
    description: Restaurant Service for placing orders
  tech:
    - Java-8
    - Spring Boot
    - Spring Cloud Eureka Client
    - Spring Boot Admin Client
    - Spring Boot Oauth Security
    